// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using priorizzeProject.Adapter.Persistence;

#nullable disable

namespace priorizzeProject.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260419025147_AddJiraProjects")]
    partial class AddJiraProjects
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("priorizzeProject.Core.Models.Cycle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasComment("ID único do ciclo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CyclesEnum")
                        .HasColumnType("int")
                        .HasComment("Trimestre do ano (1=Q1, 2=Q2, 3=Q3, 4=Q4)");

                    b.Property<int>("Year")
                        .HasColumnType("int")
                        .HasComment("Ano do ciclo");

                    b.HasKey("Id");

                    b.ToTable("Cycles", null, t =>
                        {
                            t.HasComment("Tabela de ciclos/trimestres");
                        });
                });

            modelBuilder.Entity("priorizzeProject.Core.Models.JiraProjects", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("JiraId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)");

                    b.Property<string>("JiraUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("LasSync")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id");

                    b.ToTable("JiraProjects", (string)null);
                });

            modelBuilder.Entity("priorizzeProject.Core.Models.MetricsHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CapturedValue")
                        .HasColumnType("int");

                    b.Property<DateTime>("RecordedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime(6)")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP(6)");

                    b.Property<int>("TargetId")
                        .HasColumnType("int");

                    b.Property<int>("TypesEnum")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("MetricsHistories", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
